### ISSUE TITLE
Come up with 4-5 suggestions of names for this challenge

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#10]
On March 18, Justin Guinney asked us to come up with 4-5 suggestions of names for this challenge.

Notes:

- The "Patient mortality Challenge" name used in some documents is too specific as this challenge will address additional questions (?)

**Comment by tschaffter** [comment]
Suggestions of challenge names are tracked here: https://docs.google.com/spreadsheets/d/1lic5nzztFwH-7upE4mA9m7vtXi-0eYc-07e0jWQW03A/edit#gid=0

**Comment by tschaffter** [comment]
@trberg Let's brain storm ideas of the challenge here. What are the components that characterize this challenge?

- Data: the use of Electronic Health Records; Are there other aspects that characterize these data?
- Clinical application: predict mortality; Are there other questions that we want to ask during this (first) challenge?
- What else?

**Comment by trberg** [comment]
@tschaffter 
Data: currently, we have data from three hospitals from the Seattle area, Harborview Medical Center, UW Medical Center, and Northwest Hospital.
Application: The first question is just mortality, but I think we'll be asking more questions in the future.
I've started a brainstorming list for the catchy name [here](https://docs.google.com/document/d/14PAr_Ha4UpVvVnTCrVOGsffHd8qlYhnzciD6y9VjaLw/edit#) on the second page. I'd love more ideas and feedback.

**Comment by tschaffter** [comment]
Thanks Tim! This is enough to have a productive discussion during our next meeting.
