### ISSUE TITLE
Provide list of organizing institutions and partners

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#12]
https://docs.google.com/spreadsheets/d/1dSFPVD_T7QprB-dzRZsFFxdmt5qGngU9EuYUY-Oy2DM/edit#gid=0

**Comment by tschaffter** [comment]
@trberg Can you do a first pass on the above document and add all the contributing organization that you know (Challenge organizer, data contributor, journal partners, sponsors, etc.)?

**Comment by trberg** [comment]
Okay, added the info. We don't currently have a journal partner, not sure
if we'll be pursuing that or not.
