### ISSUE TITLE
Provide synthetic data to Sage for infrastructure development and testing

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#15]
- Upload synthetic data, for example to [EHR Challenge Staging project](https://www.synapse.org/#!Synapse:syn18405992/files/)

**Comment by tschaffter** [comment]
@yy6linda I see the file [synpuf.zip](https://www.synapse.org/#!Synapse:syn18420930) in EHR Challenge Staging project. Can you confirm that this is what we should use for developing the IT infrastructure?

**Comment by yy6linda** [comment]
Yes

**Comment by tschaffter** [comment]
Thanks!
