### ISSUE TITLE
Test challenge infrastructure at UW

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#23]
@thomasyu888 tested the challenge infrastructure on Sage network using a part of the Synpuf data and one of Yao's model. The goal of this task is for Tim to confirm that he can run the infrastructure on UW network using the instructions provided by Tim. Once done, the next step will be to have the infrastructure deployed by NCATS.

**Comment by tschaffter** [comment]
@trberg Do you have an update regarding this task?

**Comment by tschaffter** [comment]
@trberg Do you have an update regarding this task?

**Comment by trberg** [comment]
@tschaffter still working on it. The new data dump put me back a little bit.

**Comment by trberg** [comment]
We have run an initial test with the new pipeline

**Comment by trberg** [comment]
@yy6linda and @trberg are going to be running a stress test on June 10 to finalize the configuration

**Comment by tschaffter** [comment]
There are issues that prevent the deployment of the challenge infrastructure on UW server. These issues are tracked in #33 and #34.

**Comment by trberg** [comment]
Infrastructure has been tested. Ongoing troubleshooting and configuration is being tracked in #34
