### ISSUE TITLE
Consider creating sub-challenges where patients are grouped by diseases

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#27]
E.g. cancer, coronary heart disease, type-II diabetes, chronic obstructive pulmonary disease.

@yy6linda Could you have a look at the number of patients who died for each of these disease?

**Comment by tschaffter** [comment]
@yy6linda As a reminder, let's not upload any information about the dataset on this GitHub repos!

**Comment by yy6linda** [comment]
@tschaffter The dataset I used to calculate the number of patients with a certain disease is a subset of the full dataset. I will re-calculate all the statistics when the full dataset is ready.

**Comment by tschaffter** [comment]
Now tracked in #16
