### ISSUE TITLE
Make a proposal for the content of the evaluation set for the Validation Phase

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#28]
- consider using both existing data and data that will be collected in the future
- report number of positive and negative subjects expected to have in this evaluation set
- make a new proposal for the timeline that include the period required to collect the data

**Comment by tschaffter** [comment]
@trberg Can you please provide an update regarding this action item?

**Comment by trberg** [comment]
Yes, we have decided to use the "prediction window" technique as described
in our data description document.
