### ISSUE TITLE
Finalize Licenses and MoU with Julie

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#30]
Send SNOMED use license language and finalize the MoU with Sean and Julie

**Comment by tschaffter** [comment]
@trberg Can you please provide an update regarding this action item?

**Comment by trberg** [comment]
Sean and Justin are still discussing the details.

**Comment by jmcmurry** [comment]
I assume this is a different Julie and not me, but please confirm.

**Comment by tschaffter** [comment]
@trberg You meant Julie Bletz, correct? Has the license and MOU been finalized?
