### ISSUE TITLE
Identify how best use the WashU synthetic dataset

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#31]
These are "meaningful" synthetic data that we could use for a sub-challenge, for example.

We have a call with Randi on June 18 between 8 and 9am PDT.

- [x] Contact Randi for additional information about the dataset (number of positive, etc.)
- [x] Depending on the number, prepare a proposal on how we recommend using the data

**Comment by tschaffter** [comment]
@jguinney @sdmooney @trberg Randi presented how the WashU data are generated. Generating a dataset for the challenge will however be difficult because the dataset generated would be missing many of the EHR tables/properties that are expected to be found in a standard EHR.

While WashU data may not be used for the challenge itself, it could be used to address additional questions after the end of the challenge. An idea was also to generate a tailored WashU dataset for each of the best-performing model so that a give dataset includes at least the EHR information corresponding to the main features used by a given model.

**Comment by tschaffter** [comment]
@jguinney @sdmooney @trberg Randi will be at the CD2H All Hands F2F Meeting and is looking forward to meet and discuss on how to best use the WashU data in the context of this EHR DREAM Challenge.

**Comment by trberg** [comment]
Currently, we are in the process of working with WashU to not just used their synthetic data, but their non-synthethic OMOP repository for this challenge.
