### ISSUE TITLE
Prepare material for the next DREAM newsletter

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#32]
From Julie:

> Hi Thomas
We are now aiming for end of July to align with an announcement for a challenge for the Allen Institute. Just plan to have something to me by mid July. 
Thanks

**Comment by tschaffter** [comment]
Note from Julie Bletz on July 5:

> I'm planning to send another DREAM newsletter at the end of this month (July).

**Comment by trberg** [comment]
@tschaffter the newsletter was sent out correct? Can we close this issue?

**Comment by tschaffter** [comment]
@trberg Yes, the EHR Challenge has been featured in the DREAM newsletter sent on August 5.
