### ISSUE TITLE
Engage CTSA centers with mortality models

### ISSUE THREAD

**Issue by jguinney** [data2health/DREAM-Challenge#36]

**Comment by tschaffter** [comment]
## Update Jan 16, 2020

- We are working closely with Erick S. to onboard Mount Sinai. Erick is participating to our weekly calls. Tim, Erick and myself have also a bi-weekly call to discuss the implementation details.
- We have resumed discussion with WashU and have started the on boarding of Ricky and Albert.

**Comment by tschaffter** [comment]
@jguinney Do you consider this task completed?

**Comment by tschaffter** [comment]
@jguinney Is this ticket still relevant?
