### ISSUE TITLE
Quota time leads models sent on the fast lane to fail

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#37]
On Monday 14, @thomasyu888 reported that models are failing on the NCATS server because they hit the maximum runtime. I believe that the maximum runtime is currently set to 1 hour.

Resolution:
- @thomasyu888 to confirm that the maximum runtime is set to 1h
- @trberg to provide an update regarding the update of the Synpuf data on the NCATS server and how to make the size of the dataset so that methods can reasonably run on it for less than 1h.

**Comment by thomasyu888** [comment]
@tschaffter. Time quota is set to one hour.

**Comment by tschaffter** [comment]
Max runtime is 1h on the NCATS server. Establishing a relationship between the max runtime on NCATS and UW server will be addressed in a separate ticket.
