### ISSUE TITLE
there are some issues on NCATS that lead submissions to stop randomly

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#38]
On Monday 14, @thomasyu888 reported that

> there are some issues on NCATS that lead submissions to stop randomly, Tom is restarting the submissions but we need a better fix.

@thomasyu888 Can you provide a better description of the issue?

**Comment by thomasyu888** [comment]
@tschaffter: https://github.com/Sage-Bionetworks/SynapseWorkflowHook/issues/50. I haven't had a chance to look at it closer

**Comment by tschaffter** [comment]
@thomasyu888 Is there an update for this issue?

**Comment by thomasyu888** [comment]
I think this was fixed in the most recent workflowhook fix, but will keep open to make sure.

**Comment by tschaffter** [comment]
I'm actually closing this ticket. We can reopen it if the issue occurs again.
