### ISSUE TITLE
Build UW infrastructure

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#4]
Pilot a pipeline that pulls docker submissions from Synapse into UW RIT environments that will train and test on UW OMOP data.

**Comment by jprosser** [comment]
Hey @trberg 
Are you good with the "con4" server in this regard?

**Comment by trberg** [comment]
I think so. Currently, we have only 2 cores available, would it be possible to scale up to a few more? @jprosser

**Comment by jprosser** [comment]
Yep, we can bump that up.  I've reserved 6, but there's room for growth there.

**Comment by tschaffter** [comment]
@trberg Is this tread redundant with #23 ?

**Comment by trberg** [comment]
The pipeline has been run through initial tests

**Comment by trberg** [comment]
@yy6linda and @trberg are going to be running a stress test on June 10 to finalize the configuration

**Comment by tschaffter** [comment]
There are currently issues that are blocking this ticket. These issues are tracked in #33 and #34.
