### ISSUE TITLE
Onboard WashU into the evaluation network.

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#41]
We are working with Randi to onboard the WashU site into the DREAM Challenge evaluation network.

**Comment by tschaffter** [comment]
Still waiting for on an update from WashU. I'll send another request for an update in the next 1-2 days.

**Comment by tschaffter** [comment]
## Update Jan 16, 2020

- We have resumed discussion with WashU and have started the on boarding of Ricky and Albert.
