### ISSUE TITLE
Problem with permissions of UW logs

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#47]
When the pipeline at UW writes the pipeline generated logfile to Synapse, the permissions are set so that only the ehrdreamservice account can access it. We need to change this so that all log files written to Synapse can be read by the submitter and by the EHR DREAM admin team.

**Comment by thomasyu888** [comment]
The logs were masked on purpose from submitters. I will add the ability for the admin team to read.

**Comment by thomasyu888** [comment]
https://github.com/Sage-Bionetworks/EHR-challenge/pull/7
