### ISSUE TITLE
Participant are unable to see their dashboard

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#48]
The dashboard shows an error similar to `is showing Index: -1, Size: 33`.

According to Tim, the dashboard is displayed if there is at least one "successfully" submission. Users with only failed submissions can not see their dashboard.

**Comment by thomasyu888** [comment]
This is a known bug in jira. Unknown when fix will occur.

**Comment by tschaffter** [comment]
Can you put the link to the JIRA ticket here? This is not the same issue as the sorting issue I encountered, right? It's a major bug if participants can not see their dashboard. We should have the software team be aware of that and make it a critical bug with top priority.

**Comment by thomasyu888** [comment]
https://sagebionetworks.jira.com/browse/PLFM-5905
The fix is to add the missing annotation key for all submissions which is rather cumbersome. Those issues are linked.

**Comment by thomasyu888** [comment]
Do you know which dashboard it is?  Is it the UW dashboard?

**Comment by tschaffter** [comment]
@trberg See Tom's comment. Can you confirm that the faulty dashboards are the ones on this page: https://www.synapse.org/#!Synapse:syn18405991/wiki/595490

**Comment by tschaffter** [comment]
@trberg Is the issue affecting only a specific table?

**Comment by tschaffter** [comment]
@thomasyu888 I believe that this issue has been fixed a long time ago. Can you provide a brief description of the solution for future references before closing this ticket? Thanks!

**Comment by thomasyu888** [comment]
Please see linked jira. The solutions are there.
