### ISSUE TITLE
Develop Synapse management pipeline

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#5]

**Comment by tschaffter** [comment]
The existing solution developed by Sage - the Synapse Workflow Hook - will be adapted to meet the requirements of the EHR Challenge. An initial version of the IT infrastructure could be deployed on Sage EC2 instances in a few days once the following requirements are met: #8

**Comment by tschaffter** [comment]
Update: Sage has developed an initial version of the challenge infrastructure that @thomasyu888 has then implemented. The infrastructure code and documentation have been provided @trberg , who is now testing it on UW.

This ticket will be closed once #23 has been completed.

**Comment by tschaffter** [comment]
Closing this ticket as the submission pipeline is ready. Testing at UW is tracked in #23.
