### ISSUE TITLE
Add data and resource information and descriptions

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#6]
Documentation: https://www.synapse.org/#!Synapse:syn18405992/wiki/589659

**Comment by tschaffter** [comment]
Documentation needs to be reviewed by:
- [x] @tschaffter 
- [x] @yy6linda

**Comment by tschaffter** [comment]
I should be able to review this documentation today or tomorrow.

**Comment by yy6linda** [comment]
I added some suggestion on the google doc provided by Thomas.  https://docs.google.com/document/d/1V2kCHHJnjHFUGiWLc09tgUYDSLo6Q3J1KoAZQkvGGSg/edit#

**Comment by tschaffter** [comment]
@trberg Have you addressed the suggestion that Yao and I shared in the above document? Is the documentation of the challenge data on the staging website complete?

**Comment by trberg** [comment]
I believe so, yes
