### ISSUE TITLE
Update write-up submission instructions

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#60]
We now want the participants to share their Synapse project (write-up) with the organizers as soon as they have submitted it. We need also to provide information on the validation process of the write-up.

On this staging page: https://www.synapse.org/#!Synapse:syn18405992/wiki/595123

- [x] Add information about 1) how to share the project and 2) the validation process (Thomas)
- [x] Create write-up dashboard that shows the submission status (Tom)
- [x] Review of the page by Tom
- [x] Review of the page by Tim
- [x] Mirror to the public site (Thomas)

**Comment by thomasyu888** [comment]
I added the dashboard here: https://www.synapse.org/#!Synapse:syn18405992/wiki/594281, but the page looks good.

**Comment by trberg** [comment]
Looks good!

**Comment by tschaffter** [comment]
Done
