### ISSUE TITLE
Finalize UW Validation Dataset

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#64]
Tim is working on finalizing the UW dataset to evaluate the final submission to the EHR DREAM Challenge: Patient Mortality Prediction.

High-level updates may be reported here (do not share sensitive information in this public repos).

**Comment by tschaffter** [comment]
## Update

- Tim is evaluating the final methods on the final dataset. When a method fails, Tim looks at the dataset and usually the issue can be resolved by updating the format of the dataset so that it reflects better the format used in the Leaderboard phase.

**Comment by trberg** [comment]
## Update
All models except two have successfully run on the validation dataset. I have reached out to the HELM team and am trying an older model that passed the leaderboard phase from PnP_India to make sure that it can pass on the validation data.

**Comment by tschaffter** [comment]
## Update

@trberg will further compare the content of the training set in the leaderboard phase and the slightly smaller version of it in the validation phase.
