### ISSUE TITLE
Ensembling prediction from the final round

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#69]
- Unweighted ensemble
  - [x] Ensemble prediction from all submitted methods (see References for the methods)
  - [ ] Ensemble predictions from top 1, top 2, top 3, etc.
- Unweighted ensemble
  - [x] Ensemble prediction from all submissions with weight *w* where *w* is the AUROC value of the method on the Leaderboard Evaluation set. Do a similar ensemble using the AUPR value as the weight and report the AUPR of the ensemble method
  - [x] Ensemble predictions from top 1, top 2, top 3, etc. with weight *w*

## References

- [Wisdom of crowds for robust gene network inference](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3512113/)

**Comment by yy6linda** [comment]
Please see this slide for ensembled model results. [Link](https://docs.google.com/presentation/d/1DuU43vUj878xWRCBdYldxXfQeI3wVse_3ipwWZzM3cM/edit#slide=id.g7757ceb7c4_0_183)
