### ISSUE TITLE
Add instructions for submissions

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#7]

**Comment by tschaffter** [comment]
The documentation will be available here: https://www.synapse.org/#!Synapse:syn18404606/wiki/589619

**Comment by tschaffter** [comment]
Blocking this ticket as we first need to finalize the format of the submission (in particular the environment variables that we want to provide).

**Comment by tschaffter** [comment]
@yy6linda Is this documentation complete?
