### ISSUE TITLE
Draft the challenge timeline

### ISSUE THREAD

**Issue by tschaffter** [data2health/DREAM-Challenge#9]
**Background:** DREAM challenges typically provides a figure representing the timeline of the challenge. This figure, which is often used in presentations too, should provide participants with the start and end date of the different phases of the challenge (open phase, leaderboard rounds, validation phase). Here is an example of timeline:

![image](https://user-images.githubusercontent.com/3056480/54643641-a35cff80-4a54-11e9-9214-7a7e5b65be90.png)

**Task:** Draft the challenge timeline, which will be displayed on the [EHR Challenge wiki](https://www.synapse.org/#!Synapse:syn18405992/wiki/589658).

**Comment by trberg** [comment]
@tschaffter I've created a draft of the challenge timeline. It is currently up on the [EHR Challenge wiki](https://www.synapse.org/#!Synapse:syn18405992/wiki/589658)
